language: generic
os: linux
dist: bionic
jobs:
  include:
    - language: python
      before_install:
        - sudo apt-get -y install gnat
        - sudo apt-get -y install gfortran
      install:
        - python3 -m pip install -r requirements.txt
      script:
        - cd test
        - python3 fulltest.py
