language: python
os: linux
dist: xenial
jobs:
  include:
    - language: python
      install:
        - python3 -m pip install -r requirements.txt
        - apt install gnat
      script:
        - cd test
        - python3 fulltest.py
