language: python
os: linux
dist: xenial
jobs:
  include:
    - language: python
      before_install:
        - sudo apt-get -y install gnat
      install:
        - python3 -m pip install -r requirements.txt
      script:
        - cd test
        - python3 fulltest.py
